<script setup>
import { ref, computed, onMounted } from 'vue'
import { useCollections } from '../stores/useCollections.js'
import { useTabs } from '../stores/useTabs.js'
import { Logger } from '../core/Logger.js'
import BaseDialog from './BaseDialog.vue'
import VariableInput from './VariableInput.vue'

const emit = defineEmits(['close'])

const collectionsStore = useCollections()
const tabsStore = useTabs()

// Create logger instance
const logger = new Logger({ prefix: 'GlobalRequestBuilder', level: 'debug' })

// Form state
const requestName = ref('')
const requestMethod = ref('GET')
const requestUrl = ref('')
const selectedCollectionId = ref('')
const createNewTab = ref(true)

// Available options
const httpMethods = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS']

const collections = computed(() => {
  return collectionsStore.collections.value || []
})

const nameInput = ref(null)

const createRequest = async () => {
  try {
    let targetCollectionId = selectedCollectionId.value

    // If no collection selected, create a new one
    if (!targetCollectionId && collections.value.length === 0) {
      const newCollection = collectionsStore.createCollection('My Collection')
      targetCollectionId = newCollection.info.id
    } else if (!targetCollectionId) {
      // Use the first available collection
      targetCollectionId = collections.value[0].info.id
    }

    // Create the request in the collection
    const newRequest = collectionsStore.addRequest(targetCollectionId, {
      method: requestMethod.value,
      url: requestUrl.value || 'https://api.example.com'
    })

    if (newRequest) {
      // Update the request name if provided
      if (requestName.value.trim()) {
        collectionsStore.updateRequest(targetCollectionId, newRequest.id, {
          name: requestName.value.trim()
        })
      }

      // Create new tab if requested
      if (createNewTab.value) {
        tabsStore.openRequest(targetCollectionId, newRequest.id)
      }
    }

    emit('close')
  } catch (error) {
    logger.error('Failed to create request:', error)
  }
}

const handleSubmit = (event) => {
  event.preventDefault()
  createRequest()
}

const closeDialog = () => {
  emit('close')
}

// Auto-generate request name based on method and URL
const autoGeneratedName = computed(() => {
  if (!requestUrl.value) return ''

  try {
    const url = new URL(requestUrl.value.startsWith('http') ? requestUrl.value : `https://${requestUrl.value}`)
    const path = url.pathname === '/' ? '' : url.pathname
    return `${requestMethod.value} ${url.hostname}${path}`
  } catch {
    return `${requestMethod.value} ${requestUrl.value}`
  }
})

// Use auto-generated name if no custom name provided
const finalRequestName = computed(() => {
  return requestName.value.trim() || autoGeneratedName.value || 'New Request'
})

// Focus the input when dialog opens
onMounted(() => {
  setTimeout(() => {
    nameInput.value?.focus()
  }, 100)
})
</script>

<template>
  <BaseDialog
    title="Create New Request"
    width="500px"
    @close="closeDialog"
  >
    <form @submit="handleSubmit" class="request-builder-form">
      <div class="form-section">
        <h3 class="section-title">Request Details</h3>

        <div class="form-group">
          <label for="request-name" class="form-label">
            Request Name (optional)
          </label>
          <input
            id="request-name"
            ref="nameInput"
            v-model="requestName"
            type="text"
            placeholder="Leave empty to auto-generate"
            class="form-input"
          />
          <p class="form-help">
            Preview: <strong>{{ finalRequestName }}</strong>
          </p>
        </div>

        <div class="form-row">
          <div class="form-group">
            <label for="request-method" class="form-label">Method</label>
            <select
              id="request-method"
              v-model="requestMethod"
              class="form-select"
            >
              <option
                v-for="method in httpMethods"
                :key="method"
                :value="method"
              >
                {{ method }}
              </option>
            </select>
          </div>

          <div class="form-group flex-1">
            <label for="request-url" class="form-label">URL</label>
            <VariableInput
              id="request-url"
              v-model="requestUrl"
              placeholder="https://api.example.com/users"
              class="form-input"
            />
          </div>
        </div>
      </div>

      <div class="form-section">
        <h3 class="section-title">Organization</h3>

        <div class="form-group">
          <label for="collection-select" class="form-label">
            Collection
          </label>
          <select
            id="collection-select"
            v-model="selectedCollectionId"
            class="form-select"
          >
            <option value="">{{ collections.length > 0 ? 'Select a collection...' : 'Create new collection' }}</option>
            <option
              v-for="collection in collections"
              :key="collection.info.id"
              :value="collection.info.id"
            >
              {{ collection.info.name }} ({{ (collection.item || []).length }} requests)
            </option>
          </select>
          <p class="form-help">
            {{ selectedCollectionId ? 'Request will be added to selected collection' : 'Request will be added to first collection or create new one' }}
          </p>
        </div>

        <div class="form-group">
          <label class="checkbox-label">
            <input
              type="checkbox"
              v-model="createNewTab"
              class="form-checkbox"
            />
            <span class="checkbox-text">Open request in new tab</span>
          </label>
        </div>
      </div>

      <div class="form-actions">
        <button
          type="button"
          class="btn-secondary"
          @click="closeDialog"
        >
          Cancel
        </button>
        <button
          type="submit"
          class="btn-primary"
        >
          Create Request
        </button>
      </div>
    </form>
  </BaseDialog>
</template>

<style scoped>
.request-builder-form {
  padding: 24px;
}

.form-section {
  margin-bottom: 32px;
}

.form-section:last-of-type {
  margin-bottom: 24px;
}

.section-title {
  font-size: 16px;
  font-weight: 600;
  color: var(--color-text-primary);
  margin: 0 0 16px 0;
  padding-bottom: 8px;
  border-bottom: 1px solid var(--color-border-light);
}

.form-group {
  margin-bottom: 16px;
}

.form-row {
  display: flex;
  gap: 16px;
  align-items: end;
}

.flex-1 {
  flex: 1;
}

.form-label {
  display: block;
  font-size: 14px;
  font-weight: 600;
  color: var(--color-text-primary);
  margin-bottom: 6px;
}

.form-input,
.form-select {
  width: 100%;
  padding: 10px 12px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  background: var(--color-bg-primary);
  color: var(--color-text-primary);
  font-size: 14px;
  transition: all 0.2s ease;
}

.form-input:focus,
.form-select:focus {
  outline: none;
  border-color: var(--color-primary);
  box-shadow: 0 0 0 3px var(--color-primary-light);
}

.form-help {
  font-size: 12px;
  color: var(--color-text-muted);
  margin: 6px 0 0 0;
  line-height: 1.4;
}

.checkbox-label {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  font-size: 14px;
  color: var(--color-text-primary);
}

.form-checkbox {
  width: 16px;
  height: 16px;
  cursor: pointer;
}

.checkbox-text {
  font-weight: 500;
}

.form-actions {
  display: flex;
  gap: 12px;
  justify-content: flex-end;
  padding-top: 16px;
  border-top: 1px solid var(--color-border-light);
}

.btn-secondary,
.btn-primary {
  padding: 10px 20px;
  border-radius: var(--radius-md);
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s ease;
  border: none;
}

.btn-secondary {
  background: var(--color-bg-tertiary);
  color: var(--color-text-secondary);
  border: 1px solid var(--color-border);
}

.btn-secondary:hover {
  background: var(--color-bg-hover);
  color: var(--color-text-primary);
}

.btn-primary {
  background: var(--color-primary);
  color: white;
}

.btn-primary:hover {
  background: var(--color-primary-dark);
  transform: translateY(-1px);
  box-shadow: var(--shadow-md);
}
</style>